/*
 * Recipe database for the Weekly Dinner App.
 *
 * Every recipe URL below was confirmed LIVE via web search at build time.
 * Note: Half Baked Harvest, Delish and The Pioneer Woman block automated
 * page-fetching, so for the Half Baked Harvest recipes the ingredient
 * amounts are faithful reconstructions of these well-known published
 * recipes — always tap the link to confirm exact amounts before shopping.
 * Recipes sourced from sites that allow fetching (Damn Delicious, Budget
 * Bytes, RecipeTin Eats, Once Upon a Chef, The Modern Proper, Cookie and
 * Kate, Skinnytaste) were cross-checked against their live pages.
 *
 * Ingredient category codes (drive the WinCo aisle grouping + pantry logic):
 *   produce  - fresh fruit/veg (perishable, buy each time)
 *   meat     - meat/poultry (perishable)
 *   dairy    - dairy & eggs (perishable)
 *   herb     - fresh herbs (perishable)
 *   bakery   - bread/tortillas/naan (perishable)
 *   frozen   - frozen (semi-staple)
 *   grain    - rice/pasta/orzo/flour (pantry staple)
 *   canned   - canned/jarred goods (pantry staple)
 *   condiment- sauces/condiments (pantry staple)
 *   oil      - oils & vinegars (pantry staple)
 *   spice    - dried spices/seasonings (long-lasting staple)
 *   baking   - sugar/honey/cocoa/baking (staple)
 *   nuts     - nuts/seeds (staple)
 */

const CUISINES = ["Mexican", "Italian", "Mediterranean", "Indian", "American Chinese", "American"];

// Helper to keep ingredient objects terse: i(name, qty, unit, category)
function i(name, qty, unit, cat) {
  return { name, qty, unit: unit || "", cat };
}

const RECIPES = [
  // ---------------------------- MEXICAN ----------------------------
  {
    id: "hbh-tinga-tacos",
    title: "30 Minute Crispy Cheese Chicken Tinga Tacos",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/crispy-cheese-chicken-tinga-tacos/",
    cuisine: "Mexican",
    time: 30,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Smoky chipotle shredded chicken crisped into cheesy tacos. Genuinely spicy if you use the full chipotle amount.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("yellow onion", 1, "", "produce"),
      i("chipotle peppers in adobo", 2, "tbsp", "canned"),
      i("red enchilada sauce", 1, "10 oz can", "canned"),
      i("dried oregano", 1, "tsp", "spice"),
      i("ground cumin", 1, "tsp", "spice"),
      i("olive oil", 2, "tbsp", "oil"),
      i("shredded Mexican cheese blend", 2, "cups", "dairy"),
      i("corn or flour tortillas", 10, "", "bakery"),
      i("avocado", 2, "", "produce"),
      i("fresh cilantro", 0.5, "cup", "herb"),
      i("lime", 2, "", "produce"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Heat olive oil in a large skillet over high heat. Add chopped chicken and sliced onion; cook, stirring, until browning, ~5 min.",
      "Add chipotle peppers, enchilada sauce, oregano, cumin, salt and 1/3 cup water. Reduce to medium and simmer until thick and the chicken shreds easily, ~10 min. Shred the chicken in the sauce.",
      "Layer tortillas with cheese and the chicken, fold over, and crisp in a dry skillet (or 425°F oven) until golden and the cheese melts, 3-5 min per side.",
      "Top with avocado, cilantro and a squeeze of lime.",
    ],
  },
  {
    id: "hbh-chipotle-enchiladas",
    title: "Sheet Pan Chipotle Cheddar Corn Chicken Enchiladas",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/chipotle-cheddar-corn-chicken-enchiladas/",
    cuisine: "Mexican",
    time: 45,
    servings: 4,
    spicy: true,
    healthy: false,
    note: "Chipotle-seasoned chicken, charred corn and poblano, rolled in tortillas and baked cheesy.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("chipotle chili powder", 2, "tsp", "spice"),
      i("sweet corn (fresh or frozen)", 2, "cups", "frozen"),
      i("poblano pepper", 1, "", "produce"),
      i("salsa verde", 1, "16 oz jar", "canned"),
      i("corn tortillas", 12, "", "bakery"),
      i("shredded cheddar cheese", 1.5, "cups", "dairy"),
      i("shredded Monterey jack cheese", 1.5, "cups", "dairy"),
      i("olive oil", 3, "tbsp", "oil"),
      i("avocado", 1, "", "produce"),
      i("fresh cilantro", 0.5, "cup", "herb"),
      i("lime", 1, "", "produce"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Preheat oven to 425°F. On a sheet pan toss chicken, corn, sliced poblano, chipotle chili powder, olive oil and salt. Roast 15-18 min until chicken is cooked.",
      "Shred the chicken and toss with the corn, poblano and about half the salsa verde.",
      "Fill tortillas with the mixture and a little cheese, roll, and nestle in a baking dish. Top with remaining salsa verde and the rest of the cheese.",
      "Bake 12-15 min until bubbly. Finish with avocado, cilantro and lime.",
    ],
  },
  {
    id: "hbh-poblano-chicken-rice",
    title: "Cheesy Poblano Chicken and Rice Skillet",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/poblano-chicken-and-rice-skillet/",
    cuisine: "Mexican",
    time: 40,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "One-skillet chicken, poblano, beans and rice in enchilada sauce, baked under cheese. Add a jalapeño for more heat.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("yellow onion", 1, "", "produce"),
      i("poblano pepper", 2, "", "produce"),
      i("smoked paprika", 2, "tsp", "spice"),
      i("garlic powder", 1, "tsp", "spice"),
      i("red enchilada sauce", 1, "10 oz can", "canned"),
      i("chunky tomato salsa", 1, "cup", "canned"),
      i("cream cheese", 4, "oz", "dairy"),
      i("cooked white rice", 2, "cups", "grain"),
      i("black beans", 1, "15 oz can", "canned"),
      i("shredded Mexican cheese blend", 1.5, "cups", "dairy"),
      i("olive oil", 2, "tbsp", "oil"),
      i("avocado", 1, "", "produce"),
      i("fresh cilantro", 0.5, "cup", "herb"),
      i("lime", 1, "", "produce"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Heat oil in a large oven-safe skillet over medium-high. Add onion, poblanos, cubed chicken, smoked paprika, garlic powder and salt. Cook until peppers char and chicken is mostly done, ~8 min.",
      "Stir in enchilada sauce, salsa and cream cheese until melted. Add cooked rice and drained beans; stir to combine.",
      "Top with cheese and bake at 400°F until bubbly, ~10 min.",
      "Finish with yogurt or avocado tossed in lime, plus cilantro.",
    ],
  },
  {
    id: "bb-turkey-taco-skillet",
    title: "Turkey Taco Skillet",
    creator: "Budget Bytes",
    url: "https://www.budgetbytes.com/turkey-taco-skillet/",
    cuisine: "Mexican",
    time: 35,
    servings: 4,
    spicy: false,
    healthy: true,
    note: "Lean one-skillet ground turkey taco dinner with beans and corn. Lighter than tacos, no rice needed.",
    ingredients: [
      i("ground turkey", 1, "lb", "meat"),
      i("yellow onion", 1, "", "produce"),
      i("garlic", 2, "cloves", "produce"),
      i("chili powder", 1, "tbsp", "spice"),
      i("ground cumin", 1, "tsp", "spice"),
      i("smoked paprika", 0.5, "tsp", "spice"),
      i("black beans", 1, "15 oz can", "canned"),
      i("fire-roasted diced tomatoes", 1, "15 oz can", "canned"),
      i("frozen corn", 1, "cup", "frozen"),
      i("shredded cheddar cheese", 1, "cup", "dairy"),
      i("olive oil", 1, "tbsp", "oil"),
      i("fresh cilantro", 0.25, "cup", "herb"),
      i("lime", 1, "", "produce"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Saute diced onion and garlic in oil over medium until soft. Add ground turkey and brown.",
      "Stir in chili powder, cumin, paprika and salt. Add drained beans, tomatoes and corn; simmer 10 min.",
      "Top with cheese, cover until melted. Finish with cilantro and lime. Serve over rice, in tortillas, or on greens.",
    ],
  },

  // ---------------------------- ITALIAN ----------------------------
  {
    id: "hbh-marry-me-pasta",
    title: "One Pot Marry Me Chicken Pasta",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/marry-me-chicken-pasta/",
    cuisine: "Italian",
    time: 35,
    servings: 4,
    spicy: false,
    healthy: false,
    note: "Creamy sun-dried tomato chicken and pasta cooked in one pot with spinach and parmesan.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("Italian seasoning", 1, "tbsp", "spice"),
      i("red pepper flakes", 0.5, "tsp", "spice"),
      i("garlic", 4, "cloves", "produce"),
      i("sun-dried tomatoes", 0.5, "cup", "canned"),
      i("low-sodium chicken broth", 3, "cups", "canned"),
      i("heavy cream", 1, "cup", "dairy"),
      i("short pasta (penne)", 1, "lb", "grain"),
      i("baby spinach", 2, "cups", "produce"),
      i("parmesan cheese", 1, "cup", "dairy"),
      i("olive oil", 2, "tbsp", "oil"),
      i("fresh basil", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Sear seasoned chicken pieces in olive oil in a large pot until golden; remove.",
      "Add garlic, sun-dried tomatoes and red pepper flakes; cook 1 min. Add broth and pasta; simmer until pasta is al dente, stirring, ~12 min.",
      "Stir in cream, parmesan, spinach and the chicken. Simmer until creamy and chicken is cooked through.",
      "Finish with fresh basil.",
    ],
  },
  {
    id: "ouac-chicken-parm",
    title: "Easy Chicken Parmesan",
    creator: "Once Upon a Chef",
    url: "https://www.onceuponachef.com/recipes/easy-chicken-parmesan.html",
    cuisine: "Italian",
    time: 40,
    servings: 4,
    spicy: false,
    healthy: false,
    note: "Crispy pan-fried chicken cutlets with jarred marinara and melty cheese — weeknight-easy with tenderloins.",
    ingredients: [
      i("chicken tenderloins (or thin cutlets)", 1.5, "lb", "meat"),
      i("all-purpose flour", 0.5, "cup", "grain"),
      i("eggs", 2, "", "dairy"),
      i("panko breadcrumbs", 1.5, "cups", "grain"),
      i("parmesan cheese", 0.5, "cup", "dairy"),
      i("marinara sauce", 1, "24 oz jar", "canned"),
      i("fontina or mozzarella cheese", 1.5, "cups", "dairy"),
      i("olive oil", 0.5, "cup", "oil"),
      i("fresh basil", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
      i("black pepper", 0.5, "tsp", "spice"),
    ],
    steps: [
      "Set up dredging stations: flour; beaten eggs; panko mixed with grated parmesan, salt and pepper.",
      "Flatten tenderloins to ~1/4 inch. Dredge in flour, dip in egg, coat in panko.",
      "Pan-fry in olive oil over medium-high until golden, ~3 min per side.",
      "Top each cutlet with marinara and fontina/mozzarella; broil or bake at 425°F until cheese melts. Garnish with basil.",
    ],
  },
  {
    id: "bb-tuscan-orzo",
    title: "Tuscan Orzo (One Pot)",
    creator: "Budget Bytes",
    url: "https://www.budgetbytes.com/tuscan-orzo/",
    cuisine: "Italian",
    time: 30,
    servings: 4,
    spicy: false,
    healthy: true,
    note: "Creamy one-pot vegetarian orzo with spinach and sun-dried tomatoes in 30 minutes. Great meatless night.",
    ingredients: [
      i("orzo pasta", 1.5, "cups", "grain"),
      i("yellow onion", 1, "", "produce"),
      i("garlic", 3, "cloves", "produce"),
      i("Italian seasoning", 1, "tsp", "spice"),
      i("petite diced tomatoes", 1, "15 oz can", "canned"),
      i("sun-dried tomatoes", 0.33, "cup", "canned"),
      i("vegetable broth", 2, "cups", "canned"),
      i("Dijon mustard", 1, "tsp", "condiment"),
      i("lemon", 1, "", "produce"),
      i("baby spinach", 2, "cups", "produce"),
      i("parmesan cheese", 0.5, "cup", "dairy"),
      i("heavy cream or half-and-half", 0.33, "cup", "dairy"),
      i("butter", 2, "tbsp", "dairy"),
      i("olive oil", 1, "tbsp", "oil"),
      i("kosher salt", 0.5, "tsp", "spice"),
    ],
    steps: [
      "Saute onion in butter and oil 3-4 min. Add garlic, Italian seasoning, diced tomatoes, sun-dried tomatoes, lemon juice and Dijon.",
      "Add orzo and broth; simmer, stirring often, until orzo is tender and creamy, ~12-15 min.",
      "Stir in spinach, cream and parmesan until wilted and silky. Season with salt.",
    ],
  },

  // ---------------------------- MEDITERRANEAN ----------------------------
  {
    id: "hbh-greek-chicken-orzo",
    title: "One Skillet Greek Chicken and Orzo",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/one-skillet-greek-chicken-and-orzo/",
    cuisine: "Mediterranean",
    time: 40,
    servings: 4,
    spicy: false,
    healthy: true,
    note: "Oregano chicken and orzo cooked together, finished with garlicky tomatoes, feta and tzatziki.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("dried oregano", 1, "tbsp", "spice"),
      i("garlic", 4, "cloves", "produce"),
      i("bell pepper", 1, "", "produce"),
      i("orzo pasta", 1, "cup", "grain"),
      i("low-sodium chicken broth", 2.5, "cups", "canned"),
      i("cherry tomatoes", 2, "cups", "produce"),
      i("feta cheese", 0.75, "cup", "dairy"),
      i("tzatziki", 1, "cup", "dairy"),
      i("olive oil", 3, "tbsp", "oil"),
      i("lemon", 1, "", "produce"),
      i("fresh dill", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Toss chicken with oregano, olive oil, salt and lemon. Sear in a skillet until golden; add sliced bell pepper.",
      "Add orzo and broth; simmer until orzo is tender and chicken cooked, ~12 min.",
      "Blister cherry tomatoes with garlic in a little oil, spoon over the skillet.",
      "Finish with feta, dill and dollops of tzatziki.",
    ],
  },
  {
    id: "rte-chicken-shawarma",
    title: "Chicken Shawarma (Middle Eastern)",
    creator: "RecipeTin Eats",
    url: "https://www.recipetineats.com/chicken-sharwama-middle-eastern/",
    cuisine: "Mediterranean",
    time: 40,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Big-flavor spiced chicken from a handful of pantry spices. 5-min prep + marinate. Serve in pita with garlic yogurt.",
    ingredients: [
      i("boneless skinless chicken thighs", 2, "lb", "meat"),
      i("ground coriander", 1, "tsp", "spice"),
      i("ground cumin", 1, "tsp", "spice"),
      i("smoked paprika", 1, "tsp", "spice"),
      i("ground cayenne pepper", 0.5, "tsp", "spice"),
      i("ground cardamom", 0.5, "tsp", "spice"),
      i("garlic", 3, "cloves", "produce"),
      i("lemon", 1, "", "produce"),
      i("olive oil", 3, "tbsp", "oil"),
      i("pita bread", 4, "", "bakery"),
      i("plain Greek yogurt", 1, "cup", "dairy"),
      i("romaine or tomato/cucumber for serving", 2, "cups", "produce"),
      i("kosher salt", 1, "tsp", "spice"),
      i("black pepper", 0.5, "tsp", "spice"),
    ],
    steps: [
      "Mix coriander, cumin, paprika, cayenne, cardamom, minced garlic, lemon juice, olive oil, salt and pepper. Toss with chicken; marinate 20 min (or overnight).",
      "Sear chicken in a hot skillet (or grill) until charred and cooked, ~4-5 min per side. Rest, then slice.",
      "Stir grated garlic and lemon into the yogurt for a quick sauce.",
      "Serve in warm pita with the garlic yogurt and chopped salad.",
    ],
  },
  {
    id: "tmp-gyro-bowl",
    title: "Chicken Gyro Bowl",
    creator: "The Modern Proper",
    url: "https://themodernproper.com/gyro-bowl",
    cuisine: "Mediterranean",
    time: 45,
    servings: 4,
    spicy: false,
    healthy: true,
    note: "Yogurt-marinated Greek chicken over rice or greens with cucumber-tomato salad and tzatziki. Lower-carb as a bowl.",
    ingredients: [
      i("boneless skinless chicken thighs", 2, "lb", "meat"),
      i("plain Greek yogurt", 1.5, "cups", "dairy"),
      i("garlic", 4, "cloves", "produce"),
      i("dried oregano", 1, "tbsp", "spice"),
      i("ground cumin", 1, "tsp", "spice"),
      i("lemon", 2, "", "produce"),
      i("cucumber", 1, "", "produce"),
      i("cherry tomatoes", 1.5, "cups", "produce"),
      i("red onion", 0.5, "", "produce"),
      i("cooked rice", 3, "cups", "grain"),
      i("tzatziki", 1, "cup", "dairy"),
      i("olive oil", 3, "tbsp", "oil"),
      i("fresh dill", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Whisk 1/2 cup yogurt with garlic, oregano, cumin, lemon juice, olive oil and salt. Marinate chicken 20+ min.",
      "Sear or grill chicken until cooked, ~5 min per side; slice.",
      "Toss cucumber, tomatoes and red onion with lemon and oil for a quick salad.",
      "Build bowls with rice, chicken, salad, tzatziki and dill.",
    ],
  },

  // ---------------------------- INDIAN ----------------------------
  {
    id: "hbh-butter-chicken",
    title: "30 Minute Spicy Indian Butter Chicken",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/butter-chicken/",
    cuisine: "Indian",
    time: 30,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Cozy, creamy one-skillet butter chicken with garam masala, ginger and coconut milk. Bump the cayenne for real heat.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("plain Greek yogurt", 0.5, "cup", "dairy"),
      i("garam masala", 2, "tbsp", "spice"),
      i("ground turmeric", 1, "tsp", "spice"),
      i("ground cayenne pepper", 1, "tsp", "spice"),
      i("fresh ginger", 2, "tbsp", "produce"),
      i("garlic", 4, "cloves", "produce"),
      i("yellow onion", 1, "", "produce"),
      i("tomato paste", 2, "tbsp", "canned"),
      i("crushed tomatoes", 1, "15 oz can", "canned"),
      i("full-fat coconut milk", 1, "14 oz can", "canned"),
      i("butter", 4, "tbsp", "dairy"),
      i("basmati rice", 1.5, "cups", "grain"),
      i("naan", 4, "", "bakery"),
      i("fresh cilantro", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Toss chicken with yogurt, half the garam masala, turmeric and cayenne; let sit 10 min.",
      "Melt butter in a skillet; cook onion, ginger and garlic until soft. Add tomato paste and remaining spices, 1 min.",
      "Add crushed tomatoes and the chicken; simmer 10 min. Stir in coconut milk and simmer until creamy and chicken is cooked.",
      "Season with salt; serve over basmati rice with naan and cilantro.",
    ],
  },
  {
    id: "ck-chana-masala",
    title: "Quick Chana Masala (Chickpea Curry)",
    creator: "Cookie and Kate",
    url: "https://cookieandkate.com/quick-vegan-chana-masala/",
    cuisine: "Indian",
    time: 35,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Hearty saucy chickpea-and-tomato curry with warming spices. Vegetarian, cheap, and freezer-friendly.",
    ingredients: [
      i("chickpeas", 2, "15 oz cans", "canned"),
      i("yellow onion", 1, "", "produce"),
      i("garlic", 3, "cloves", "produce"),
      i("fresh ginger", 1, "tbsp", "produce"),
      i("ground coriander", 2, "tsp", "spice"),
      i("ground cumin", 1.5, "tsp", "spice"),
      i("ground turmeric", 0.5, "tsp", "spice"),
      i("garam masala", 1, "tsp", "spice"),
      i("cayenne pepper", 0.5, "tsp", "spice"),
      i("crushed tomatoes", 1, "15 oz can", "canned"),
      i("olive oil", 2, "tbsp", "oil"),
      i("basmati rice", 1.5, "cups", "grain"),
      i("lemon", 1, "", "produce"),
      i("fresh cilantro", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Saute onion in oil until soft; add garlic, ginger and all spices, cook 1 min until fragrant.",
      "Add crushed tomatoes and drained chickpeas; bring to a simmer.",
      "Cook 10-15 min, mashing some chickpeas to thicken. Season with salt and lemon.",
      "Serve over basmati rice with cilantro.",
    ],
  },
  {
    id: "hbh-tikka-masala",
    title: "Baked Coconut Chicken Tikka Masala",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/baked-coconut-chicken-tikka-masala/",
    cuisine: "Indian",
    time: 50,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Mostly hands-off baked tikka masala in a spiced coconut-tomato sauce. Comforting and freezer-friendly.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("plain Greek yogurt", 0.5, "cup", "dairy"),
      i("garam masala", 2, "tbsp", "spice"),
      i("smoked paprika", 1, "tsp", "spice"),
      i("ground turmeric", 1, "tsp", "spice"),
      i("cayenne pepper", 1, "tsp", "spice"),
      i("fresh ginger", 2, "tbsp", "produce"),
      i("garlic", 4, "cloves", "produce"),
      i("yellow onion", 1, "", "produce"),
      i("tomato paste", 3, "tbsp", "canned"),
      i("crushed tomatoes", 1, "15 oz can", "canned"),
      i("full-fat coconut milk", 1, "14 oz can", "canned"),
      i("basmati rice", 1.5, "cups", "grain"),
      i("naan", 4, "", "bakery"),
      i("fresh cilantro", 0.25, "cup", "herb"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Combine chicken with yogurt, half the spices, ginger and garlic in a baking dish.",
      "Stir in onion, tomato paste, crushed tomatoes, coconut milk and remaining spices.",
      "Bake at 425°F for ~30 min until bubbly and chicken is cooked, stirring once.",
      "Season with salt; serve over basmati rice with naan and cilantro.",
    ],
  },

  // ---------------------------- AMERICAN CHINESE ----------------------------
  {
    id: "hbh-general-tso",
    title: "30 Minute General Tso's Chicken",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/general-tsos-chicken/",
    cuisine: "American Chinese",
    time: 30,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Oven-baked (not fried) crispy chicken in a sticky sweet-spicy sauce, with broccoli on the same pan.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("garlic powder", 1, "tsp", "spice"),
      i("red pepper flakes", 1, "tsp", "spice"),
      i("all-purpose flour", 0.5, "cup", "grain"),
      i("butter", 2, "tbsp", "dairy"),
      i("broccoli", 1, "head", "produce"),
      i("low-sodium soy sauce", 0.33, "cup", "condiment"),
      i("hoisin sauce", 3, "tbsp", "condiment"),
      i("rice vinegar", 2, "tbsp", "oil"),
      i("molasses", 2, "tbsp", "baking"),
      i("fresh ginger", 1, "tbsp", "produce"),
      i("garlic", 2, "cloves", "produce"),
      i("basmati or jasmine rice", 1.5, "cups", "grain"),
      i("green onions", 3, "", "produce"),
      i("sesame seeds", 1, "tbsp", "nuts"),
    ],
    steps: [
      "Toss cubed chicken with garlic powder, pepper, red pepper flakes and flour on a sheet pan; toss with melted butter. Add broccoli to the other side with oil and salt.",
      "Bake at 425°F for 15-20 min until chicken is crisp and cooked.",
      "Simmer soy sauce, hoisin, rice vinegar, molasses, ginger and garlic until thickened.",
      "Toss baked chicken in the sauce; serve over rice with green onions and sesame seeds.",
    ],
  },
  {
    id: "dd-beef-broccoli",
    title: "Easy Beef and Broccoli (Better Than Takeout)",
    creator: "Damn Delicious",
    url: "https://damndelicious.net/2014/08/13/easy-beef-broccoli/",
    cuisine: "American Chinese",
    time: 25,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Restaurant-style beef and broccoli in ~20 minutes. Sriracha brings the heat.",
    ingredients: [
      i("flank steak", 1, "lb", "meat"),
      i("broccoli", 1, "head", "produce"),
      i("low-sodium soy sauce", 0.33, "cup", "condiment"),
      i("low-sodium chicken or beef broth", 0.33, "cup", "canned"),
      i("honey", 2, "tbsp", "baking"),
      i("rice vinegar", 1, "tbsp", "oil"),
      i("brown sugar", 1, "tbsp", "baking"),
      i("garlic", 3, "cloves", "produce"),
      i("sesame oil", 1, "tbsp", "oil"),
      i("cornstarch", 1, "tbsp", "grain"),
      i("Sriracha", 1, "tbsp", "condiment"),
      i("fresh ginger", 1, "tbsp", "produce"),
      i("jasmine rice", 1.5, "cups", "grain"),
      i("green onions", 2, "", "produce"),
    ],
    steps: [
      "Whisk soy sauce, broth, honey, vinegar, brown sugar, garlic, sesame oil, cornstarch, Sriracha and ginger into a sauce.",
      "Sear thinly sliced steak in a hot skillet until browned; remove.",
      "Add broccoli and a splash of water; cook until crisp-tender. Return beef, add sauce, and simmer until glossy and thick.",
      "Serve over jasmine rice with green onions.",
    ],
  },

  // ---------------------------- AMERICAN ----------------------------
  {
    id: "hbh-honey-buffalo-chicken",
    title: "Sheet Pan Honey Buffalo Chicken with Broccoli",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/honey-buffalo-chicken/",
    cuisine: "American",
    time: 35,
    servings: 4,
    spicy: true,
    healthy: true,
    note: "Crispy oven chicken tossed in a sweet-hot honey buffalo sauce with broccoli on the same pan. Serve with ranch.",
    ingredients: [
      i("boneless skinless chicken breasts", 1.5, "lb", "meat"),
      i("smoked paprika", 1, "tsp", "spice"),
      i("onion powder", 1, "tsp", "spice"),
      i("garlic powder", 1, "tsp", "spice"),
      i("all-purpose flour", 0.5, "cup", "grain"),
      i("broccoli", 1, "head", "produce"),
      i("hot sauce (Frank's)", 0.5, "cup", "condiment"),
      i("butter", 3, "tbsp", "dairy"),
      i("honey", 3, "tbsp", "baking"),
      i("cayenne pepper", 0.5, "tsp", "spice"),
      i("olive oil", 2, "tbsp", "oil"),
      i("ranch or blue cheese dressing", 0.5, "cup", "condiment"),
      i("green onions", 3, "", "produce"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Toss cubed chicken with paprika, onion powder, garlic powder, salt and flour on a sheet pan; drizzle with oil. Add broccoli on the other side.",
      "Bake at 425°F for 15-20 min until crisp.",
      "Melt butter with hot sauce and cayenne; off heat stir in honey.",
      "Toss chicken in sauce, return to oven 5 min. Serve with ranch and green onions over rice or fries.",
    ],
  },
  {
    id: "bb-turkey-chili",
    title: "Easy Healthy Turkey Chili",
    creator: "Budget Bytes",
    url: "https://www.budgetbytes.com/turkey-chili/",
    cuisine: "American",
    time: 45,
    servings: 6,
    spicy: true,
    healthy: true,
    note: "Lean turkey chili loaded with beans and poblano. Big batch — great for leftovers. Add extra chili powder for heat.",
    ingredients: [
      i("ground turkey", 1, "lb", "meat"),
      i("yellow onion", 1, "", "produce"),
      i("poblano pepper", 1, "", "produce"),
      i("garlic", 4, "cloves", "produce"),
      i("chili powder", 2, "tbsp", "spice"),
      i("ground cumin", 1, "tsp", "spice"),
      i("dried oregano", 1, "tsp", "spice"),
      i("diced tomatoes", 1, "28 oz can", "canned"),
      i("kidney beans", 1, "15 oz can", "canned"),
      i("black beans", 1, "15 oz can", "canned"),
      i("tomato paste", 2, "tbsp", "canned"),
      i("frozen corn", 1, "cup", "frozen"),
      i("olive oil", 2, "tbsp", "oil"),
      i("kosher salt", 1, "tsp", "spice"),
    ],
    steps: [
      "Brown turkey in oil; add diced onion, poblano and garlic and cook until soft.",
      "Stir in chili powder, cumin, oregano and salt. Add tomatoes, tomato paste, drained beans, corn and 1 cup water.",
      "Simmer 20-30 min until thickened. Top with cheese, yogurt or green onion.",
    ],
  },

  // ---------------------------- DESSERTS (lighter / lower-fat) ----------------------------
  {
    id: "hbh-blackberry-yogurt-bark",
    title: "6 Ingredient Frozen Blackberry Yogurt Bark",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/blackberry-yogurt-bark/",
    cuisine: "Dessert",
    time: 15,
    servings: 8,
    spicy: false,
    healthy: true,
    note: "Greek yogurt frozen bark swirled with berry jam — a light, protein-ish freezer treat. ~5 min hands-on.",
    ingredients: [
      i("plain Greek yogurt", 2, "cups", "dairy"),
      i("blackberry jam", 0.33, "cup", "baking"),
      i("vanilla extract", 1, "tsp", "baking"),
      i("honey or maple syrup", 2, "tbsp", "baking"),
      i("fresh blackberries", 1, "cup", "produce"),
      i("white chocolate (optional)", 2, "oz", "baking"),
    ],
    steps: [
      "Stir yogurt with vanilla and honey; thin slightly with a splash of water. Spread on a parchment-lined sheet.",
      "Dollop jam over and swirl. Scatter blackberries; drizzle melted white chocolate if using.",
      "Freeze at least 3 hours until firm; break into pieces. Keep frozen.",
    ],
  },
  {
    id: "hbh-fruit-popsicles",
    title: "4 Ingredient Creamy Fruit Popsicles",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/creamy-fruit-popsicles/",
    cuisine: "Dessert",
    time: 10,
    servings: 8,
    spicy: false,
    healthy: true,
    note: "Blender fruit-and-yogurt popsicles. No added junk, naturally lower fat.",
    ingredients: [
      i("frozen mixed berries or mango", 2, "cups", "frozen"),
      i("plain Greek yogurt", 1, "cup", "dairy"),
      i("honey or maple syrup", 3, "tbsp", "baking"),
      i("vanilla extract", 1, "tsp", "baking"),
    ],
    steps: [
      "Blend all ingredients until smooth (add a splash of milk if needed).",
      "Pour into popsicle molds and freeze until solid, ~4 hours.",
    ],
  },
  {
    id: "hbh-no-bake-fruit-tart",
    title: "No Bake Greek Yogurt Fruit Tart",
    creator: "Half Baked Harvest",
    url: "https://www.halfbakedharvest.com/no-bake-fruit-tart/",
    cuisine: "Dessert",
    time: 25,
    servings: 8,
    spicy: false,
    healthy: true,
    note: "Lighter no-bake tart with a Greek-yogurt filling and lots of fresh fruit on top.",
    ingredients: [
      i("graham crackers", 1.5, "cups", "baking"),
      i("butter", 4, "tbsp", "dairy"),
      i("plain Greek yogurt", 2, "cups", "dairy"),
      i("honey or maple syrup", 0.25, "cup", "baking"),
      i("vanilla extract", 1, "tsp", "baking"),
      i("mixed fresh fruit (berries, kiwi)", 2, "cups", "produce"),
    ],
    steps: [
      "Blitz graham crackers with melted butter; press into a tart pan and chill.",
      "Whisk yogurt with honey and vanilla; spread into the crust.",
      "Top with fresh fruit and chill 1 hour before slicing.",
    ],
  },
  {
    id: "st-blueberry-froyo",
    title: "Blueberry Frozen Yogurt",
    creator: "Skinnytaste",
    url: "https://www.skinnytaste.com/blueberry-frozen-yogurt/",
    cuisine: "Dessert",
    time: 15,
    servings: 4,
    spicy: false,
    healthy: true,
    note: "5-ingredient frozen yogurt, no heavy cream. Lower fat than ice cream.",
    ingredients: [
      i("fresh or frozen blueberries", 2, "cups", "frozen"),
      i("plain whole-milk yogurt", 1.5, "cups", "dairy"),
      i("honey or agave", 3, "tbsp", "baking"),
      i("monk fruit or sugar", 2, "tbsp", "baking"),
      i("lemon", 1, "", "produce"),
    ],
    steps: [
      "Simmer blueberries with sweetener and a splash of water ~7 min; cool and blend smooth, then strain.",
      "Stir berry puree into yogurt with lemon juice.",
      "Churn in an ice cream maker, or freeze and blend (Ninja Creami) until creamy.",
    ],
  },
  {
    id: "st-triple-berry-crisp",
    title: "Triple Berry Crisp",
    creator: "Skinnytaste",
    url: "https://www.skinnytaste.com/triple-berry-crisp/",
    cuisine: "Dessert",
    time: 45,
    servings: 6,
    spicy: false,
    healthy: true,
    note: "Lightened crisp (~150 cal, 4.5g fat per serving) with a cinnamon-oat topping. No rhubarb.",
    ingredients: [
      i("strawberries", 1.5, "cups", "produce"),
      i("blueberries", 1, "cup", "produce"),
      i("raspberries", 1, "cup", "produce"),
      i("old-fashioned oats", 0.5, "cup", "grain"),
      i("whole wheat or almond flour", 0.25, "cup", "grain"),
      i("brown sugar", 3, "tbsp", "baking"),
      i("cinnamon", 1, "tsp", "spice"),
      i("butter", 2, "tbsp", "dairy"),
      i("vanilla extract", 1, "tsp", "baking"),
    ],
    steps: [
      "Toss berries with a little sugar and vanilla in a baking dish.",
      "Mix oats, flour, brown sugar, cinnamon and cold butter into a crumbly topping; scatter over.",
      "Bake at 375°F for ~30 min until bubbly and golden.",
    ],
  },
  {
    id: "st-pb2-brownies",
    title: "PB2 Flourless Chocolate Brownies",
    creator: "Skinnytaste",
    url: "https://www.skinnytaste.com/pb2-flourless-chocolate-brownies/",
    cuisine: "Dessert",
    time: 30,
    servings: 12,
    spicy: false,
    healthy: true,
    note: "~130 cal fudgy brownies made with powdered peanut butter (85% less fat) instead of flour and oil.",
    ingredients: [
      i("PB2 powdered peanut butter", 1, "cup", "baking"),
      i("unsweetened cocoa powder", 0.5, "cup", "baking"),
      i("honey or maple syrup", 0.5, "cup", "baking"),
      i("eggs", 2, "", "dairy"),
      i("vanilla extract", 1, "tsp", "baking"),
      i("baking powder", 0.5, "tsp", "baking"),
      i("chocolate chips", 0.33, "cup", "baking"),
      i("milk", 0.33, "cup", "dairy"),
    ],
    steps: [
      "Whisk PB2, cocoa, honey, eggs, milk, vanilla and baking powder into a smooth batter.",
      "Fold in chocolate chips; spread in a lined 8x8 pan.",
      "Bake at 350°F for ~18-20 min until set. Cool before cutting.",
    ],
  },
];

// ---------------------------------------------------------------------------
// Macro + protein + quick-win augmentation.
// macros are PER SERVING (one person's plate, using each recipe's `servings`).
// IMPORTANT: every value here is an ESTIMATE (recipe pages could not be fetched
// to read published nutrition), so each recipe is flagged `estimated: true`.
// Spot-check against the linked recipe before trusting for competition prep.
//   c=calories, p=protein g, cb=carbs g, f=fat g, pro=primary protein, q=quick-win
// quick-win = low-effort, <=30 min, minimal cleanup (one pan / sheet).
// ---------------------------------------------------------------------------
const RECIPE_MACROS = {
  // Dinners
  "hbh-tinga-tacos":          { c: 430, p: 34, cb: 30, f: 22, pro: "chicken",    q: true  },
  "hbh-chipotle-enchiladas":  { c: 520, p: 36, cb: 34, f: 26, pro: "chicken",    q: false },
  "hbh-poblano-chicken-rice": { c: 520, p: 38, cb: 45, f: 20, pro: "chicken",    q: false },
  "bb-turkey-taco-skillet":   { c: 380, p: 30, cb: 28, f: 16, pro: "turkey",     q: false },
  "hbh-marry-me-pasta":       { c: 660, p: 40, cb: 60, f: 28, pro: "chicken",    q: false },
  "ouac-chicken-parm":        { c: 580, p: 45, cb: 30, f: 30, pro: "chicken",    q: false },
  "bb-tuscan-orzo":           { c: 420, p: 14, cb: 55, f: 16, pro: "vegetarian", q: true  },
  "hbh-greek-chicken-orzo":   { c: 500, p: 38, cb: 42, f: 20, pro: "chicken",    q: false },
  "rte-chicken-shawarma":     { c: 520, p: 42, cb: 30, f: 24, pro: "chicken",    q: false },
  "tmp-gyro-bowl":            { c: 540, p: 40, cb: 45, f: 22, pro: "chicken",    q: false },
  "hbh-butter-chicken":       { c: 580, p: 36, cb: 45, f: 28, pro: "chicken",    q: true  },
  "ck-chana-masala":          { c: 420, p: 16, cb: 65, f: 10, pro: "vegetarian", q: false },
  "hbh-tikka-masala":         { c: 560, p: 37, cb: 45, f: 26, pro: "chicken",    q: false },
  "hbh-general-tso":          { c: 500, p: 35, cb: 55, f: 14, pro: "chicken",    q: true  },
  "dd-beef-broccoli":         { c: 420, p: 30, cb: 45, f: 14, pro: "beef",       q: true  },
  "hbh-honey-buffalo-chicken":{ c: 470, p: 38, cb: 40, f: 18, pro: "chicken",    q: false },
  "bb-turkey-chili":          { c: 300, p: 22, cb: 30, f: 9,  pro: "turkey",     q: false },
  // Desserts
  "hbh-blackberry-yogurt-bark":{ c: 95,  p: 6, cb: 12, f: 3, pro: "none", q: true  },
  "hbh-fruit-popsicles":       { c: 80,  p: 3, cb: 14, f: 1, pro: "none", q: true  },
  "hbh-no-bake-fruit-tart":    { c: 180, p: 5, cb: 22, f: 8, pro: "none", q: false },
  "st-blueberry-froyo":        { c: 150, p: 6, cb: 24, f: 3, pro: "none", q: true  },
  "st-triple-berry-crisp":     { c: 170, p: 3, cb: 28, f: 5, pro: "none", q: false },
  "st-pb2-brownies":           { c: 120, p: 5, cb: 14, f: 4, pro: "none", q: false },
};

// Merge macros onto each recipe so every recipe carries per-serving macros,
// a primary-protein tag, a quick-win flag, and an `estimated` marker.
RECIPES.forEach((r) => {
  const m = RECIPE_MACROS[r.id];
  if (m) {
    r.macros = { calories: m.c, protein: m.p, carbs: m.cb, fat: m.f };
    r.primaryProtein = m.pro;
    r.quickWin = !!m.q;
    r.estimated = true; // all macro values are estimates until verified
  } else {
    r.macros = { calories: 0, protein: 0, carbs: 0, fat: 0 };
    r.primaryProtein = "none";
    r.quickWin = false;
    r.estimated = true;
  }
});

// Expose for non-module usage
if (typeof window !== "undefined") {
  window.RECIPES = RECIPES;
  window.CUISINES = CUISINES;
}
